### ISSUE TITLE
Touscreen impossible to do anything

### ISSUE THREAD

**Issue by Yoken0S** [Insiderser/AutoFullscreen#3]
Hi,

I use your Addon for some specifics production lines but there is a little problem with our Touchscreens monitor.
As there is no mouse or keyboard it is impossible to get the menu back.
Indeep the touchscreen doesn't pop the toolbar even if we press the topest we can. It is perfect for security but people can't even leave or refresh the page ^^"

I don't know if there is a solution to that but if you find something it would be great.

**Comment by insiderser** [comment]
Hi. What OS do you use?

**Comment by Yoken0S** [comment]
Hi, Windows 10 IoT

**Comment by insiderser** [comment]
I see swiping with 2 fingers from the top of the screen should make Firefox exit the full-screen mode on Windows. Does it work for you?

Also, I don't quite understand your use case. You want the toolbar to be always hidden, but with the ability to bring it back, which in turn would allow users to open any webpage or close Firefox and navigate around in Windows as they wish.

**Comment by insiderser** [comment]
Hey @Yoken0S. If this issue is still relevant, do you mind creating an issue with Mozilla at https://bugzilla.mozilla.org/home, please?

How the full-screen mode looks on Firefox is controlled by Firefox. This plugin has the same effect as if the user pressed the F11 key. It just does that automatically when a new Firefox window is created. And I have no intention of changing that behavior, i.e. creating a custom full-screen mode without Firefox's built-in implementation.

Let me know if you still have any other issues.
