### ISSUE TITLE
Bookmarks Bar

### ISSUE THREAD

**Issue by ch4pz** [Insiderser/AutoFullscreen#6]
**Describe the bug**
I REALLY love this app, not sure why its not default, but whenever i enable the app, the bookmarks bar disappears (even when manually setting always on), which is unfortunately a deal breaker as most my browsing is done off these links. Also im using Waterfox
**To Reproduce**
2. Click on the add-on
3. Open '....'
4. See error as described

**Expected behavior**
the bookmark bar to appear with the URL and Tabs when i goto the top

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11 x64
 - Waterfox version G6.0.2
 - Add-on version 2.0.4

**Additional context**

**Comment by insiderser** [comment]
Hey @ch4pz. Thanks for reporting this issue!

You can enable showing the bookmarks bar in fullscreen mode by following the steps described in https://support.mozilla.org/en-US/questions/1374693. I use it personally. Kindly let me know if the link resolves your issue.

**Please note (legal disclaimer): The link above is shared on informational basis, and I am not responsible for any damage or data loss that might occur while doing those steps, in particular by doing something wrong.**

I intentionally want to keep this add-on simple. I want it to do only one thing. All this add-on does is just "pressing" the F11 key when a new Firefox window is opened. Everything after that is the default in-fullscreen-mode Firefox experience. Modifying that experience is something outside the scope of this add-on.

But let me know if you think this add-on should do more. Maybe I should include links like the above into the add-on's description so that other folks can more easily discover them.

**Comment by ch4pz** [comment]
Hi, thanks for getting back to me! I'll definitely give it a shot. Thanks mate!!
