### ISSUE TITLE
Not working when not in full-screen window mode, solution: 

### ISSUE THREAD

**Issue by fromthedarkestpast** [Insiderser/AutoFullscreen#8]
**Is your feature request related to a problem? Please describe.**
Not working when not in full-screen window mode

**Describe the solution you'd like**
Add another app, that would also work when onlky part of screen is used for window with the extention enabled. Thanks

**Comment by insiderser** [comment]
Hey @fromthedarkestpast . What browser and browser version do you use? What's your operating system? Can you provide any more details about what issue you're facing (more detailed description, maybe screenshots, videos)? What happens when you press the F11 key on your keyboard while a Firefox window is focused?
